on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Job to compile your rom, and output as a GH asset.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./tools/github-action-build
        id: nesrom
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: rom
          path: rom
          
    