on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Build
      # uses: ./tools/github-action-build
      #  id: nesrom
      - run: pwd && ls
      - run: cd tools/tmx2c/src && npm install
        name: Npm install 1
      - run: cd tools/sprite_def2img/src && npm install
        name: Npm install 2
      - run: cd tools/chr2img/src && npm install
        name: Npm install 3
      - run: cd tools && mkdir cc65 || echo "Dir Exists" && cd cc65 && wget https://cpprograms-nes-games-https.s3.amazonaws.com/cc65setup.zip && unzip cc65setup.zip
        name: cc65 setup
      - run: CI_BUILD=true make
        name: Rom Build
      - run: mkdir $GITHUB_WORKSPACE/rom || echo "Dir exists" 
        name: Rom prep
      - run: cp rom/starter.nes $GITHUB_WORKSPACE/rom/game.nes
        name: Rom copy
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Game Download
          path: rom/game.nes
          
    