on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./tools/github-action-build
        id: nesrom
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: game.nes
          path: /github/workspace/starter.nes
          
    